//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitool.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multitool.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.betterttv.net/3/cached/users/twitch/{0}.
        /// </summary>
        internal static string BttvChannelEmotesEndpoint {
            get {
                return ResourceManager.GetString("BttvChannelEmotesEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.betterttv.net/emote/{0}/{1}.
        /// </summary>
        internal static string BttvEmoteEndpoint {
            get {
                return ResourceManager.GetString("BttvEmoteEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.betterttv.net/3/cached/emotes/global.
        /// </summary>
        internal static string BttvGlobalEmotesEndpoint {
            get {
                return ResourceManager.GetString("BttvGlobalEmotesEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\emotes cache\.
        /// </summary>
        internal static string EmoteCacheFolder {
            get {
                return ResourceManager.GetString("EmoteCacheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.frankerfacez.com/v1/{0}.
        /// </summary>
        internal static string FfzApiServerUrl {
            get {
                return ResourceManager.GetString("FfzApiServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.7tv.app/v2/users/{0}/emotes.
        /// </summary>
        internal static string SevenTVApiChannelEmotesEndPoint {
            get {
                return ResourceManager.GetString("SevenTVApiChannelEmotesEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.7tv.app/v2/emotes/global.
        /// </summary>
        internal static string SevenTVApiGlobalEmotesEndPoint {
            get {
                return ResourceManager.GetString("SevenTVApiGlobalEmotesEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/helix/chat/emotes?broadcaster_id={0}.
        /// </summary>
        internal static string TwitchApiChannelEmoteEndPoint {
            get {
                return ResourceManager.GetString("TwitchApiChannelEmoteEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/helix/chat/emotes/set.
        /// </summary>
        internal static string TwitchApiGetEmoteSetsEndPoint {
            get {
                return ResourceManager.GetString("TwitchApiGetEmoteSetsEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/helix/users?login={0}.
        /// </summary>
        internal static string TwitchApiGetUsersByLoginEndpoint {
            get {
                return ResourceManager.GetString("TwitchApiGetUsersByLoginEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/helix/chat/emotes/global.
        /// </summary>
        internal static string TwitchApiGlobalEmotesEndPoint {
            get {
                return ResourceManager.GetString("TwitchApiGlobalEmotesEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://id.twitch.tv/oauth2/validate.
        /// </summary>
        internal static string TwitchOAuthValidationUrl {
            get {
                return ResourceManager.GetString("TwitchOAuthValidationUrl", resourceCulture);
            }
        }
    }
}
