using Microsoft.Win32.SafeHandles;

using System;
using System.Drawing;
using System.Runtime.InteropServices;

using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.UI.WindowsAndMessaging;

namespace Multitool.NTInterop
{
    /// <summary>
    /// Class to hold p/invoke wrapper methods generated by Win32 C# projections.
    /// </summary>
    public static class InteropWrapper
    {
        [DllImport("user32.dll")]
        static extern bool GetCursorPos(out ulong _lpPoint);

        /// <summary>
        /// Get the absolute current cursor position as a <see cref="Point"/>.
        /// </summary>
        /// <returns>The absolute cursor position</returns>
        public static Point GetCursorPosition()
        {
            if (!GetCursorPos(out ulong pos))
            {
                throw InteropHelper.GetLastError("Failed to get cursor position ('GetCursorPos')");
            }
            int x = (int)(pos & 0x00000000FFFFFFFF);
            int y = (int)((pos & 0xFFFFFFFF00000000) >> 32);
            return new Point(x, y);
        }

        /// <summary>
        /// Get the absolute current cursor position.
        /// </summary>
        /// <param name="x">to hold the x position of the cursor</param>
        /// <param name="y">to hold the y position of the cursor</param>
        public static void GetCursorPosition(out int x, out int y)
        {
            if (!GetCursorPos(out ulong pos))
            {
                throw InteropHelper.GetLastError("Failed to get cursor position ('GetCursorPos')");
            }
            x = (int)(pos & 0x00000000FFFFFFFF);
            y = (int)((pos & 0xFFFFFFFF00000000) >> 32);
        }

        /// <summary>
        /// Sets a window position.
        /// </summary>
        /// <param name="windowHandle">HWND for the window</param>
        /// <param name="newPosition">the new position of the window</param>
        public static void SetWindowSize(object window, Windows.Foundation.Size size, Windows.Graphics.PointInt32 position = default)
        {
            HWND hwnd = (HWND)WinRT.Interop.WindowNative.GetWindowHandle(window);
            // Win32 uses pixels and WinUI 3 uses effective pixels, so you should apply the DPI scale factor
            uint dpi = PInvoke.GetDpiForWindow(hwnd);
            float scalingFactor = (float)dpi / 96;
            int width = (int)size.Width;
            int height = (int)size.Height;
            width = (int)(width * scalingFactor);
            height = (int)(height * scalingFactor);

            SET_WINDOW_POS_FLAGS flags = SET_WINDOW_POS_FLAGS.SWP_NOZORDER;
            if (position == default)
            {
                flags |= SET_WINDOW_POS_FLAGS.SWP_NOMOVE;
            }
            else
            {
                flags |= SET_WINDOW_POS_FLAGS.SWP_ASYNCWINDOWPOS;
            }

            if (!PInvoke.SetWindowPos(hwnd, default, position.X, position.Y, width, height, flags))
            {
                throw InteropHelper.GetLastError("Failed to set window position/size.");
            }
        }
    }
}
